spring.application.name=Adaptive-API-Rate-Limiter
rate.limiter.capacity=10
rate.limiter.refill-rate=2.0
rate.limiter.window-duration=60000
rate.limiter.clean-windows-required=5
rate.limiter.recovery-factor=1.1
rate.limiter.floor-percent=0.10
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING>REDIS_PORT:6379}
